### PR TITLE
Update the linear-gradient() function to new syntax. Close #73

### LINKED ISSUE #73: Autoprefixer: Gradient has outdated direction syntax. New syntax is like "to left" instead of "right".
I was trying to compile the sass files with gulp-autoprefixer.

However the autoprefixer shows error:

**"Gradient has outdated direction syntax. New syntax is like "to left" instead of "right"."**

_$ubtn-use-compass is set to false_

### PR DESCRIPTION
**Pull request by meteorlxy**
Update the linear-gradient() function to new syntax. Issue #73.

BTW, why there is no official package on npm?

### CODE REVIEW

**Comment by alexwolfe** [comment]
@roblevintennis mind taking a peak at this one?

**Comment by roblevintennis** [comment]
@alexwolfe not going to have time for a bit .. slammed at work

**Comment by alexwolfe** [comment]
No worries I'll take a look

**Comment by roblevintennis** [comment]
@alexwolfe I'm in the process of trying to update our app to the buttons-2 branch, and noticed this in our webpack compile (I believe the warning was via autoprefixer). In any event, I changed `to bottom` and the warnings went away

**Comment by alexwolfe** [comment]
Thanks Rob, appreciate it amigo!

**Comment by roblevintennis** [comment]
@alexwolfe and fwiw, I'm now spot checking buttons on pages and their rendering as expected (I think) ... this is probably fine to merge

**Comment by alexwolfe** [comment]
Cool, thanks again man!

**Comment by roblevintennis** [comment]
image

Kinda posting back as I see things lol, sorry, but here's the raised button in the app after changing syntax (using v2 Buttons, but the raised buttons appear to be the same).

**Comment by gwleuverink** [comment]
Having the same problem here. Any news?

**Comment by roblevintennis** [comment]
@gwleuverink sorry, yeah, I just merged this..Alex and I have trouble finding time to maintain. If you don't mind, could you just pull down latest and ensure we didn't break something in a major way? Thanks .. cc / @meteorlxy thanks for PR. If you have a spare moment, your code was merged and I don't have time to verify nothing broke. Thanks in advanced and sorry for the delay!

**Comment by gwleuverink** [comment]
Hi @roblevintennis. Thanks for your quick reply and making time to adress this. I have been running a fork with this fix in a project since this morning and have not noticed any issues with compiling or the buttons themselves. I will swap the repo on monday to confirm this pr works as well.

**Comment by meteorlxy** [comment]
@roblevintennis Never mind, finally merged~  
Don't worry, this is a systax update of this css function (see: [`linear-gradient`](https://developer.mozilla.org/en-US/docs/Web/CSS/linear-gradient)) and won't break anything. I've been using this PR in my own projects.

**Comment by roblevintennis** [comment]
awesome .. thanks @meteorlxy !

**Comment by gwleuverink** [comment]
Yep it works perfectly. Tested it today.

**Comment by roblevintennis** [comment]
great thx for confirmation @gwleuverink cc / @alexwolfe .. are we porting these up to the unicorn-ui version buttons 2 version? I sort of lost track of which branch has "buttons 2"

**Pull request merged**
